%% parameter setting
% % data organization
% 'tiles/[UTM code]/latitude band/square/[year]/[month]/[day]/[sequence]/DATA'
% 'tiles/    32    /      U      /  PU  / 2017 /   4   /  24 /     0    /B02.jp2'

% UTMcode = '32'; % munich belongs to
% latitudeBd = 'U';
% square = 'PU';
% year = '2017';
% month = '4';
% day = '24';
% sequence = '0';

% % amazon sentinel 2 server
websitePath = 'http://sentinel-s2-l1c.s3.amazonaws.com/';

% % local directory
% localPath = 'D:\Original_test_data\sentinel\sentinel_2\rong\';

% UTM_code    = { '32'    '32'    '32'    '32'    '32'    '32'    '32'    '32'    '32'    '32'    '32'};
% latitudeBd  = { 'U'     'U'     'U'     'U'     'U'     'U'     'U'     'U'     'U'     'U'     'U'};
% square      = { 'PU'    'PU'    'PU'    'PU'    'PU'    'PU'    'PU'    'PU'    'PU'    'PU'    'PU'};
% year        = { '2015'	'2015'  '2015'  '2015'  '2015'  '2015'  '2016'  '2016'  '2016'  '2016'  '2016'};
% month       = { '7'     '8'     '9'     '10'    '11'    '12'    '1'     '2'     '3'     '4'     '5'};
% day         = {'4'      '3'     '12'    '12'    '24'    '24'    '30'    '12'    '10'    '29'    '22'};
% sequence    = {'1'      '1'     '3'     '0'     '0'     '0'     '0'     '0'     '0'     '0'     '0'};


% % local directory
localPath = 'D:\Original_test_data\sentinel\sentinel_2\shenzhen\';
% shenzhen
% cloud coverage < 5%
% 2015.07.01 --- 2017.08.04
dataPath =...
    {...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/GE/2017/7/29/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HE/2017/7/29/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KK/2017/7/29/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/GF/2017/7/29/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/7/29/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/7/21/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KK/2017/4/2/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HE/2017/4/2/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/4/2/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/4/2/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/3/3/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/GF/2017/2/14/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HE/2017/2/14/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KK/2017/2/14/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HE/2017/2/11/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/2/11/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/2/11/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/2/4/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/2/4/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/GE/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HE/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KK/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/GF/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/1/25/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/50/Q/KL/2017/1/2/0/',...
    'http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/49/Q/HF/2017/1/2/0/'...
    
    };


UTM_code    = cell(1,length(dataPath));
latitudeBd  = cell(1,length(dataPath));
square      = cell(1,length(dataPath));
year        = cell(1,length(dataPath));
month       = cell(1,length(dataPath));
day         = cell(1,length(dataPath));
sequence    = cell(1,length(dataPath));


for i = 1:length(dataPath)
    temp = strsplit(dataPath{i},'/');
    UTM_code{i}    = temp{4};
    latitudeBd{i}  = temp{5};
    square{i}      = temp{6};
    year{i}        = temp{7};
    month{i}       = temp{8};
    day{i}         = temp{9};
    sequence{i}    = temp{10};
end





%% initial

% the true color image (TCI.jp2) is not included since it is not in every
% data set. 
fileNames = {...
    'B01.jp2',...
    'B02.jp2',...
    'B03.jp2',...
    'B04.jp2',...
    'B05.jp2',...
    'B06.jp2',...
    'B07.jp2',...
    'B08.jp2',...
    'B09.jp2',...
    'B10.jp2',...
    'B11.jp2',...
    'B12.jp2',...
    'B8A.jp2',...
    'metadata.xml',...
    'preview.jpg',...
    'productInfo.json',...
    'tileInfo.json'};



field1 = 'UTMcode';
field2 = 'latitudeBd';
field3 = 'square';
field4 = 'year';
field5 = 'month';
field6 = 'day';
field7 = 'sequence';


para = struct(field1,UTM_code,  ...
              field2,latitudeBd,...
              field3,square,    ...
              field4,year,      ...
              field5,month,     ...
              field6,day,       ...
              field7,sequence   ...                          
              );
            
% % parameter{1} = '36';        % UTM code
% % parameter{2} = 'J';         % latitudeBd = 'J';
% % parameter{3} = 'UM';        % square = 'UM';
% % parameter{4} = '2017';      % year = '2017';
% % parameter{5} = '5';         % month = '5';
% % parameter{6} = '19';        % day = '19';
% % parameter{7} = '0';         % sequence = '0';


%% downloading ...
for i = 1:length(para)
    % 
    tileStr = ['tiles/',para(i).UTMcode,'/',para(i).latitudeBd,'/',para(i).square,'/',para(i).year,'/',para(i).month,'/',para(i).day,'/',para(i).sequence,'/'];
    tileName = ['tiles_',para(i).UTMcode,'_',para(i).latitudeBd,'_',para(i).square,'_',para(i).year,'_',para(i).month,'_',para(i).day,'_',para(i).sequence,'\'];
    
    if exist([localPath,tileName], 'file') == 0
        mkdir([localPath,tileName]);
    end
    options = weboptions('Timeout',10);

    for j = 1:length(fileNames)
        filepath = [localPath,tileName,fileNames{j}];
        url = [websitePath,tileStr,fileNames{j}];
        websave(filepath,url,options);
    end
    
end









