function output = fTdet(data)

output = data(:,:,1).*data(:,:,2).*data(:,:,3)+2*real(...
    (data(:,:,4)+j*data(:,:,7)).*(data(:,:,5)-j*data(:,:,8)).*...
    (data(:,:,6)+j*data(:,:,9)))-(data(:,:,1).*(data(:,:,6).^2+data(:,:,9).^2)...
    +data(:,:,2).*(data(:,:,5).^2+data(:,:,8).^2)+...
    data(:,:,3).*(data(:,:,4).^2+data(:,:,7).^2));
output = abs(output);